### ISSUE TITLE
problems with null values

### ISSUE THREAD

**Issue by AlexECP** [nkornel/reactible#1]
For a text and select fields, when field data is loaded from view, and the data-fieldValue / data-fieldSelected is null, there is no way to edit the field, there should be some sort of placeholder.

For multiple-select, with same null value case, the plugin doesnt load, with the error:
```Uncaught SyntaxError: Unexpected end of input```

Also, for multiple select, if all options are deselected, it does not save.

**Comment by AlexECP** [comment]
Mostly fixed.  Remaining issues:
text and select-multiple: when saving a blank value, it saves the string 'null' into the DB, should really be setting to null.  Probably related is that the select-multiple doesnt show any value or placeholder after saving to null.  

text: If value is really null in DB, it shows the field name, instead of a placeholder.

**Comment by nkornel** [comment]
* Related to the ```null``` issue, we agreed to use an empty string.

* The select-multiple should show the placeholder in case of a ```null``` value after saving, not just when the control is reopened.

* Text fields should show the ```name``` of the field as a placeholder.

**Comment by AlexECP** [comment]
although the text field is now showing the placeholder after saving to `null`, it still shows the name of the field instead when reopening the dialog.

regular (non-multiple) select should also show the placeholder in case of a `null` value after saving, not just when the control is reopened.

**Comment by AlexECP** [comment]
not resolved: regular (non-multiple) select should also show the placeholder in case of a null value after saving, not just when the control is reopened.

**Comment by nkornel** [comment]
We agreed on putting ```!EMPTY!``` explicitly as in case of a default null value to maintain consistency in the API. So I think this is not an issue. Instead of ```{"":"","A":"A","B":"B","C":"C"}``` it should be  ```{"!EMPTY!":"","A":"A","B":"B","C":"C"}```

**Comment by AlexECP** [comment]
I tired this, and it still doesnt work... it works on your end?  Please pull the latest master branch, refresh and seed, and try it with the sample account.
