### ISSUE TITLE
fieldSource for single select

### ISSUE THREAD

**Issue by AlexECP** [nkornel/reactible#4]
It seems there is an issue with the select element, when fieldSource is set to a URL.  

I think it is a mixed keys issue, when `{"account":"account","meta":"meta"}` is put directly into `fieldSource` via the view, it works, but when it calls the same data response via URL, it gives `Uncaught SyntaxError: Unexpected token a`

**Comment by nkornel** [comment]
The JSON ```parse``` method for the ```fieldSource``` with ```string``` type keys was incorrect. Updated with the correct parsing formatting.

**Comment by AlexECP** [comment]
Although URL now works, it now gives the same error when loading directly from view
