### ISSUE TITLE
select-multiple selected fields

### ISSUE THREAD

**Issue by AlexECP** [nkornel/reactible#5]
another mixed keys issue.  When select-multiple has the `data-fieldSelected` attribute set with string options (ex. `["lookup","list"]`) when the lookup dialog is loaded, it shows the selected values correctly.  But when the field is clicked on for editing, none of the options are pre-selected.  In this example, the data-source is set to `{"list":"list","lookup":"lookup"}`.  If its changed to use integer keys, it works.

**Comment by nkornel** [comment]
The ```selectedField``` JSON ```parse``` method incorrectly treated ```string``` type keys in the arrays. Updated.
